dist: trusty
sudo: required
language:
    - cpp

compiler:
    - g++

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - llvm-toolchain-precise-3.8
    packages:
      - g++-6
      - clang-3.8
      - lcov

notifications:
    email: false

# Install project dependencies
install:
    - "[ $CXX = g++ ] && export CXX=g++-6 || true"
    - "[ $CXX = clang++ ] && export CXX=clang++-3.8 || true"
    - bash get_dependencies.sh

# Build the project
script:
    - bash server/build.sh
    - bash server/build_and_run_ut.sh
    - bash ins-node/build_and_run_ut.sh

after_success:
    - bash run_coverage.sh
    # Upload report to codecov
    - bash <(curl -s https://codecov.io/bash) -f ./coverage.info || echo "Codecov did not collect coverage reports"
